In [1]:
#Import the libraries 
import numpy as np
import scipy as sp
import pandas as pd
import gzip
from time import sleep
from timeit import Timer
from numpy.linalg import inv
import matplotlib.pyplot as plt
from pandas import DataFrame, read_csv
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [2]:
%cd ~/mhardist/DSE210/20news-bydate
!ls
url = 'http://qwone.com/~jason/20Newsgroups'

/Users/mikihardisty/Documents/DSE/mhardist/DSE210/20news-bydate
20news-bydate-test  20news-bydate-train

In [49]:
vocab = pd.read_csv('../vocabulary.txt', header=None)
vocab.columns = ['word']
vocab['my_index'] = [a for a in range(1,len(vocab)+1)]
vocab

                  word  my_index
0              archive         1
1                 name         2
2              atheism         3
3            resources         4
4                  alt         5
5                 last         6
6             modified         7
7             december         8
8              version         9
9              atheist        10
10           addresses        11
11                  of        12
12       organizations        13
13                 usa        14
14             freedom        15
15                from        16
16            religion        17
17          foundation        18
18              darwin        19
19                fish        20
20              bumper        21
21            stickers        22
22                 and        23
23            assorted        24
24               other        25
25       paraphernalia        26
26                 are        27
27           available        28
28                 the        29
29                  in        30
...                ...       ...
61158       sectarians     61159
61159          talmage     61160
61160      preexistent     61161
61161             exod     61162
61162  tetragrammation     61163
61163           triune     61164
61164             adon     61165
61165          atoning     61166
61166          tidings     61167
61167           maketh     61168
61168        spreadeth     61169
61169         bhagwans     61170
61170          anchovy     61171
61171      vanishingly     61172
61172         ktikkane     61173
61173           ramses     61174
61174          orontes     61175
61175        chariotry     61176
61176             amun     61177
61177            deist     61178
61178         devoutly     61179
61179           smugly     61180
61180         tartaros     61181
61181          bibical     61182
61182           tophet     61183
61183        aeroplane     61184
61184           gosple     61185
61185            ephas     61186
61186         kltensme     61187
61187           etrbom     61188

[61188 rows x 2 columns]

In [21]:
vocab[vocab[0] == 'cohesion']

             0
2739  cohesion

In [16]:
train_data = pd.read_csv('../20news-bydate2/matlab/train.data', delim_whitespace=True, header=0, names=['col1','col2','col3'])
len(set(train_data['col2']))

53975

In [33]:
train_data[train_data['col1'] == 2]

     col1  col2  col3
768     2    12     4
769     2    16     2
770     2    23     4
771     2    27     2
772     2    29     6
773     2    30     3
774     2    33     5
775     2    39     2
776     2    42     2
777     2    44     1
778     2    51     1
779     2    52     1
780     2    60     1
781     2    84     1
782     2   139     3
783     2   144     2
784     2   233     7
785     2   234     1
786     2   235     1
787     2   277     1
788     2   297     2
789     2   299     1
790     2   304     1
791     2   310     1
792     2   340     1
793     2   368     3
794     2   460     2
795     2   473     1
796     2   492     1
797     2   536     1
..    ...   ...   ...
863     2   826     1
864     2   827     1
865     2   828     1
866     2   829     1
867     2   830     1
868     2   831     1
869     2   832     1
870     2   833     1
871     2   834     2
872     2   835     1
873     2   836     1
874     2   837     1
875     2   838     1
876     2   839     1
877     2   840     1
878     2   841     1
879     2   842     1
880     2   843     1
881     2   844     1
882     2   845     1
883     2   846     1
884     2   847     1
885     2   848     2
886     2   849     1
887     2   850     2
888     2   851     1
889     2   852     1
890     2   853     1
891     2   854     1
892     2   855     1

[125 rows x 3 columns]

In [18]:
!more 20news-bydate-train/alt.atheism/51060

From: mathew <mathew@mantis.co.uk>
Subject: Alt.Atheism FAQ: Introduction to Atheism
Summary: Please read this file before posting to alt.atheism
Keywords: FAQ, atheism
Expires: Thu, 6 May 1993 12:22:45 GMT
Distribution: world
Organization: Mantis Consultants, Cambridge. UK.
Supersedes: <19930308134439@mantis.co.uk>
Lines: 646

Archive-name: atheism/introduction
Alt-atheism-archive-name: introduction
Last-modified: 5 April 1993
Version: 1.2

-----BEGIN PGP SIGNED MESSAGE-----

                          An Introduction to Atheism
                       by mathew <mathew@mantis.co.uk>

This article attempts to provide a general introduction to atheism.  Whilst I
have tried to be as neutral as possible regarding contentious issues, you
should always remember that this document represents only one viewpoint.  I
>

In [31]:
!more ../20news-bydate2/matlab/train.data

1 1 4
1 2 2
1 3 10
1 4 4
1 5 2
1 6 1
1 7 1
1 8 1
1 9 3
1 10 9
1 11 2
1 12 58
1 13 1
1 14 4
1 15 2
1 16 13
1 17 6
1 18 2
1 19 4
1 20 6
1 21 1
1 22 1
1 23 54
>

In [ ]:
!ls

In [ ]:
!more train.data

In [ ]:
http://qwone.com/~jason/20Newsgroups/vocabulary.txt