In [33]:
import numpy as np
import pandas as pd
from pandas import DataFrame, read_csv
%cd ~/mhardist/DSE210/20news-bydate
train_data = pd.read_csv('../20news-bydate2/matlab/train.data', delim_whitespace=True, header=0, names=['col1','col2','col3'])
print 'Number of docs', len(set(train_data['col1']))
print 'Number of words in docs', len(set(train_data['col2']))

train_data[train_data['col1'] == 1] #darwin

/Users/mikihardisty/Documents/DSE/mhardist/DSE210/20news-bydate
Number of docs 11269
Number of words in docs 53975

     col1  col2  col3
0       1     2     2
1       1     3    10
2       1     4     4
3       1     5     2
4       1     6     1
5       1     7     1
6       1     8     1
7       1     9     3
8       1    10     9
9       1    11     2
10      1    12    58
11      1    13     1
12      1    14     4
13      1    15     2
14      1    16    13
15      1    17     6
16      1    18     2
17      1    19     4
18      1    20     6
19      1    21     1
20      1    22     1
21      1    23    54
22      1    24     3
23      1    25     3
24      1    26     1
25      1    27    11
26      1    28     2
27      1    29    90
28      1    30    20
29      1    31     3
..    ...   ...   ...
738     1   740     1
739     1   741     1
740     1   742     1
741     1   743     1
742     1   744     1
743     1   745     1
744     1   746     1
745     1   747     1
746     1   748     1
747     1   749     1
748     1   750     1
749     1   751     3
750     1   752     2
751     1   753     2
752     1   754     2
753     1   755     2
754     1   756     1
755     1   757     1
756     1   758     1
757     1   759     1
758     1   760     1
759     1   761     1
760     1   762     2
761     1   763     1
762     1   764     1
763     1   765     1
764     1   766     1
765     1   767     1
766     1   768     1
767     1   769     1

[768 rows x 3 columns]

In [51]:
#!find . -name '49960'
!more 20news-bydate-train/sci.crypt/14147

From: Marc VanHeyningen <mvanheyn@cs.indiana.edu>
Subject: RIPEM Frequently Asked Questions
Content-Type: text/x-usenet-FAQ; version=1.0; title="RIPEM FAQ"
Originator: mvanheyn@silver.ucs.indiana.edu
Supersedes: <1993Jan25.113427.28926@news.cs.indiana.edu>
Nntp-Posting-Host: silver.ucs.indiana.edu
Organization: Computer Science, Indiana University
Expires: Fri, 30 Apr 1993 00:00:00 GMT
Lines: 255

Archive-name: ripem/faq
Last-update: Sun, 7 Mar 93 21:00:00 -0500

ABOUT THIS POSTING
------------------
This is a (still rather rough) listing of likely questions and
information about RIPEM, a program for public key mail encryption.  It
(this FAQ, not RIPEM) was written and will be maintained by Marc
VanHeyningen, <mvanheyn@whale.cs.indiana.edu>.  It will be posted to a
variety of newsgroups on a monthly basis; follow-up discussion specific
to RIPEM is redirected to the group alt.security.ripem.

This month, I have reformatted this posting in an attempt to comply
>

In [28]:
train_label = pd.read_csv('../20news-bydate2/matlab/train.label', delim_whitespace=True) #, header=0, names=['col1','col2','col3'])
train_label.columns = ['label']
set(train_label['label'])

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}

In [29]:
train_map = pd.read_csv('../20news-bydate2/matlab/train.map', delim_whitespace=True) #, header=0, names=['col1','col2','col3'])
train_map

                 alt.atheism   1
0              comp.graphics   2
1    comp.os.ms-windows.misc   3
2   comp.sys.ibm.pc.hardware   4
3      comp.sys.mac.hardware   5
4             comp.windows.x   6
5               misc.forsale   7
6                  rec.autos   8
7            rec.motorcycles   9
8         rec.sport.baseball  10
9           rec.sport.hockey  11
10                 sci.crypt  12
11           sci.electronics  13
12                   sci.med  14
13                 sci.space  15
14    soc.religion.christian  16
15        talk.politics.guns  17
16     talk.politics.mideast  18
17        talk.politics.misc  19
18        talk.religion.misc  20